<template>
  <Page>
    <div v-if="$hasPerm('risk.view_report_history')">
      <el-table v-loading="loading" :data="runs" size="small">
        <el-table-column prop="report_id" :label="$t('Report ID')" width="120" />
        <el-table-column prop="template_key" :label="$t('Report')" />
        <el-table-column prop="owner_name" :label="$t('Generated By')" width="140" />
        <el-table-column :label="$t('Period')" width="200">
          <template #default="{ row }">{{ row.period_start }} - {{ row.period_end }}</template>
        </el-table-column>
        <el-table-column prop="format" :label="$t('Format')" width="80" />
        <el-table-column :label="$t('Watermark')" width="100">
          <template #default="{ row }">
            <el-tag size="small" :type="row.watermark ? 'success' : 'info'">
              {{ row.watermark ? $t('Yes') : $t('No') }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column :label="$t('Status')" width="110">
          <template #default="{ row }">
            <el-tag size="small" :type="statusType(row.status)">{{ $t(row.status) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column :label="$t('Delivery')" width="110">
          <template #default="{ row }">
            <el-tag size="small" :type="statusType(row.delivery_status)">{{ $t(row.delivery_status) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="file_size" :label="$t('File Size')" width="90" />
        <el-table-column :label="$t('Actions')" width="160" fixed="right">
          <template #default="{ row }">
            <el-button
              v-if="row.status === 'COMPLETED' && !row.is_file_expired"
              size="small"
              @click="download(row)"
            >{{ $t('Download') }}</el-button>
            <span v-else-if="row.is_file_expired" class="expired-hint">{{ $t('File expired') }}</span>
            <el-button
              v-if="$hasPerm('risk.delete_report_history')"
              size="small"
              type="danger"
              plain
              @click="remove(row)"
            >{{ $t('Delete') }}</el-button>
          </template>
        </el-table-column>
      </el-table>
      <div class="pagination">
        <el-pagination
          background layout="prev, pager, next" :total="total"
          :page-size="pageSize" @current-change="onPageChange"
        />
      </div>
    </div>
    <Page403 v-else />
  </Page>
</template>

<script>
import { Page } from '@/layout/components'
import Page403 from '@/views/403'
import { getReportRuns, deleteReportRun, downloadReportRunUrl } from '@/api/reportsCenter'
import { message } from '@/utils/vue/message'
import { ElMessageBox } from 'element-plus'

export default {
  name: 'ReportHistory',
  components: { Page, Page403 },
  data() {
    return {
      loading: false,
      runs: [],
      total: 0,
      pageSize: 20,
      page: 1
    }
  },
  mounted() {
    if (this.$hasPerm('risk.view_report_history')) {
      this.load()
    }
  },
  methods: {
    statusType(status) {
      return { COMPLETED: 'success', SENT: 'success', FAILED: 'danger', RUNNING: 'warning', PENDING: 'warning', QUEUED: 'info', NOT_REQUESTED: 'info' }[status] || 'info'
    },
    async load() {
      this.loading = true
      try {
        const resp = await getReportRuns({ limit: this.pageSize, offset: (this.page - 1) * this.pageSize })
        this.runs = resp.results || resp
        this.total = resp.count || this.runs.length
      } finally {
        this.loading = false
      }
    },
    onPageChange(page) {
      this.page = page
      this.load()
    },
    download(row) {
      window.open(downloadReportRunUrl(row.id), '_blank')
    },
    async remove(row) {
      await ElMessageBox.confirm(this.$t('Delete this report history entry?'), this.$t('Confirm'), { type: 'warning' })
      await deleteReportRun(row.id)
      message.success(this.$t('Deleted'))
      this.load()
    }
  }
}
</script>

<style lang="scss" scoped>
.pagination {
  margin-top: 16px;
  display: flex;
  justify-content: flex-end;
}
.expired-hint {
  color: var(--color-text-secondary, #909399);
  font-size: 12px;
}
</style>
